# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://communicationanimale.tk" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: La Communication Animale
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "TPE : Que permettent les nouvelles connaissances en matière de communication animale ?" # used by search engines

  # Header and footer text
  header_text: >
     <p>Que permettent les nouvelles connaissances en matière de communication animale ?</p>

  header_text_feature_image:
  footer_text: >
   Créé par des élèves du <a href="http://www.lycee-delacroix-maisons-alfort.fr/">Lycée Delacroix</a>
   <br>2015

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-59973342-1" # tracking id, e.g. "UA-000000-01"
  disqus_shortname:

  # Localization strings
  str_follow_on: "Suivre sur"
  str_rss_follow: "S'abonner au flux RSS"
  str_email: "Email"
  str_next: "Suivant"
  str_prev: "Précédent"
  str_continue_reading: "Lire la suite"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
kramdown:
   math_engine: mathjax 
sass:
  sass_dir: _sass
  style: :compressed
exclude: ["vendor", "TeX"]

# Collections
collections:
  tpe:
    output: true
    permalink: /:collection/:title/
